"""Pure C++ emitters for validated projection schemas.

Every function in this module is deterministic and side-effect free. File-system
publication belongs to projection_codegen.py.
"""

from __future__ import annotations

from collections.abc import Iterable, Sequence

from projection_schema import MODULES, ProjectionSchema, Symbol, SymbolVersion


GENERATED_NOTICE = "// Generated by Scripts/projection_codegen.py. Do not edit."


class StringPool:
    def __init__(self) -> None:
        self.data = bytearray(b"\0")
        self.offsets: dict[str, int] = {"": 0}

    def add(self, value: str | None) -> int:
        if value is None:
            return 0
        if value in self.offsets:
            return self.offsets[value]
        encoded = value.encode("utf-8") + b"\0"
        offset = len(self.data)
        self.data.extend(encoded)
        self.offsets[value] = offset
        return offset

    def cpp_literal(self) -> str:
        pieces: list[str] = []
        for byte in self.data:
            if byte == 0:
                pieces.append("\\0")
            elif byte == 0x5C:
                pieces.append("\\\\")
            elif byte == 0x22:
                pieces.append('\\"')
            elif 0x20 <= byte < 0x7F:
                pieces.append(chr(byte))
            else:
                pieces.append(f"\\x{byte:02x}")
        return '"' + "".join(pieces) + '"'


def condition_lines(condition: str | None, lines: Iterable[str]) -> list[str]:
    values = list(lines)
    if condition == "debug":
        return ["#ifdef _DEBUG", *values, "#endif"]
    return values


def generated_comment_lines(notes: str | list[str] | None, indent: str = "\t") -> list[str]:
    if notes is None:
        return []
    values = notes if isinstance(notes, list) else [notes]
    lines: list[str] = []
    for note in values:
        for line in note.splitlines():
            lines.append(f"{indent}//{f' {line}' if line else ''}")
    return lines


def generate_layout_header(schema: ProjectionSchema) -> str:
    namespace = schema["namespace"]
    tag = schema["tag"]
    module = schema["module"]
    lines = [
        GENERATED_NOTICE,
        "#pragma once",
        "",
        f"namespace {namespace}",
        "{",
        f"\tstruct {tag};",
        "\textern Projection::ModuleRegistry g_registry;",
        "}",
        "",
        f"namespace {namespace}::Generated",
        "{",
        f"\textern LONG g_{module}SelectedOffsets[];",
        f"\textern bool g_{module}LayoutSupported[];",
        "}",
        "",
        "namespace OpenGlass::Projection",
        "{",
        f"\ttemplate <> inline ModuleRegistry& RegistryFor<{namespace}::{tag}>() noexcept",
        "\t{",
        f"\t\treturn {namespace}::g_registry;",
        "\t}",
        "",
        f"\ttemplate <> struct LayoutState<{namespace}::{tag}>",
        "\t{",
        "\t\tstatic __forceinline LONG Offset(size_t index) noexcept",
        "\t\t{",
        f"\t\t\treturn {namespace}::Generated::g_{module}SelectedOffsets[index];",
        "\t\t}",
        "",
        "\t\tstatic __forceinline bool IsSupported(size_t index) noexcept",
        "\t\t{",
        f"\t\t\treturn {namespace}::Generated::g_{module}LayoutSupported[index];",
        "\t\t}",
        "\t};",
        "}",
        "",
        f"namespace {namespace}",
        "{",
        "",
    ]
    module_notes = generated_comment_lines(schema.get("notes"))
    if module_notes:
        lines.extend([*module_notes, ""])
    for index, layout in enumerate(schema["layouts"]):
        handle = "VtableSlotHandle" if layout["kind"] == "vtable_slot" else "FieldHandle"
        layout_notes = generated_comment_lines(layout.get("notes"))
        if layout_notes:
            lines.extend(layout_notes)
        lines.append(f"\tinline constexpr Projection::{handle}<{tag}, {index}, {layout['type']}> {layout['name']}{{}};")
        if layout_notes:
            lines.append("")
    lines.extend(["}", ""])
    return "\n".join(lines)


def symbol_cpp_type(symbol: Symbol) -> str:
    return symbol.get("type") or f"decltype({symbol['target']})"


def generate_symbol_header(schema: ProjectionSchema) -> str:
    namespace = schema["namespace"]
    tag = schema["tag"]
    lines = [GENERATED_NOTICE, "#pragma once", "", f"namespace {namespace}", "{", ""]
    for index, symbol in enumerate(schema["symbols"]):
        declaration = f"\tinline constexpr Projection::SymbolHandle<{tag}, {index}, {symbol_cpp_type(symbol)}> {symbol['name']}{{}};"
        lines.extend(condition_lines(symbol.get("condition"), [declaration]))
    lines.extend(["}", ""])
    return "\n".join(lines)


def requirement_cpp(value: str) -> str:
    return "Required" if value == "required" else "Optional"


def generate_registry_inc(schemas: Sequence[ProjectionSchema]) -> str:
    lines = [GENERATED_NOTICE, ""]
    for schema in schemas:
        module = schema["module"]
        namespace = schema["namespace"]
        pool = StringPool()
        symbol_name_offsets: list[int] = []
        versions: list[tuple[str, str]] = [("0", "0")]
        version_indices: dict[tuple[str, str], int] = {("0", "0"): 0}

        def add_version(build: str, revision: str) -> int:
            key = (build, revision)
            if key not in version_indices:
                version_indices[key] = len(versions)
                versions.append(key)
            return version_indices[key]

        def add_json_version(value: SymbolVersion | None) -> int:
            if value is None:
                return 0
            return add_version(f"{value['build']}u", f"{value.get('revision', 0)}u")

        symbol_rows: list[str] = []
        binding_rows: list[str] = []
        binding_assertions: list[str] = []
        case_rows: list[str] = []
        case_assertions: list[str] = []
        layout_rows: list[str] = []
        for index, symbol in enumerate(schema["symbols"]):
            first_name_index = len(symbol_name_offsets)
            symbol_name_offsets.extend(pool.add(candidate) for candidate in symbol["symbol_names"])
            id_offset = pool.add(symbol["id"])
            minimum_index = add_json_version(symbol.get("min_inclusive"))
            maximum_index = add_json_version(symbol.get("max_exclusive"))
            requirement = f"Projection::Requirement::{requirement_cpp(symbol['requirement'])}"
            flags = "Projection::SymbolFlags::DebugOnly" if symbol.get("condition") == "debug" else "Projection::SymbolFlags::None"
            symbol_rows.append(
                f"\t{{{id_offset}, {first_name_index}, {len(symbol['symbol_names'])}, {minimum_index}, {maximum_index}, {requirement}, {flags}}},"
            )
            if symbol["kind"].startswith("projected_"):
                target = symbol["target"]
                if symbol["kind"] == "projected_function":
                    fallback = symbol.get("fallback") or f"Projection::ProjectedFailFast<{target}>"
                    storage = f"Projection::ProjectedSlotStorage<{target}>()"
                    fallback_value = f"Projection::ProjectedAddress({fallback})"
                    binding_assertions.append(
                        f"\tstatic_assert(std::is_convertible_v<decltype({fallback}), Projection::projected_abi_t<{target}>>, "
                        f"\"fallback ABI mismatch: {symbol['id']}\");"
                    )
                    compatibility = symbol.get("abi_compatibility")
                    if compatibility == "discard_return":
                        binding_assertions.append(
                            f"\tstatic_assert(Projection::is_discard_return_compatible_v<{symbol['type']}, "
                            f"Projection::projected_abi_t<{target}>>, \"discard-return ABI mismatch: {symbol['id']}\");"
                        )
                    elif compatibility == "extra_trailing_argument":
                        binding_assertions.append(
                            f"\tstatic_assert(Projection::is_extra_trailing_argument_compatible_v<{symbol['type']}, "
                            f"Projection::projected_abi_t<{target}>>, \"trailing-argument ABI mismatch: {symbol['id']}\");"
                        )
                else:
                    storage = f"Projection::ProjectedVariableStorage<{target}>()"
                    fallback_value = "nullptr"
                binding_rows.append(f"\t{{{index}, {storage}, {fallback_value}}},")

        first_case = 0
        for layout in schema["layouts"]:
            for case in layout["cases"]:
                if case.get("otherwise") is True:
                    boundary_index = 0
                else:
                    until = case["until"]
                    boundary_index = add_version(until["build"], until.get("revision", "0"))
                expression = case["offset"]
                case_assertions.append(
                    f"\tstatic_assert(static_cast<LONGLONG>({expression}) >= static_cast<LONGLONG>(INT32_MIN) && "
                    f"static_cast<LONGLONG>({expression}) <= static_cast<LONGLONG>(INT32_MAX), "
                    f"\"layout offset does not fit LONG storage: {layout['id']}\");"
                )
                case_rows.append(f"\t{{static_cast<LONG>({expression}), {boundary_index}}},")
            layout_rows.append(f"\t{{{first_case}, {len(layout['cases'])}}},")
            first_case += len(layout["cases"])

        generated_namespace = f"{namespace}::Generated"
        lines.extend([
            f"namespace {generated_namespace}",
            "{",
            f"\tconstexpr char g_{module}StringPool[] = {pool.cpp_literal()};",
            f"\tconstexpr size_t g_{module}SymbolNameOffsets[] =",
            "\t{",
            *[f"\t\t{offset}," for offset in symbol_name_offsets],
            "\t};",
            f"\tconstexpr Projection::Version g_{module}Versions[] =",
            "\t{",
            *[f"\t\t{{{build}, {revision}}}," for build, revision in versions],
            "\t};",
            f"\tconstexpr Projection::SymbolSpec g_{module}SymbolSpecs[] =",
            "\t{",
            *symbol_rows,
            "\t};",
            f"\tPVOID g_{module}Candidates[std::size(g_{module}SymbolSpecs)]{{}};",
            f"\tPVOID g_{module}Resolved[std::size(g_{module}SymbolSpecs)]{{}};",
            f"\tProjection::ResolutionState g_{module}ResolutionStates[std::size(g_{module}SymbolSpecs)]{{}};",
            *binding_assertions,
            f"\tconst Projection::BindingSpec g_{module}Bindings[] =",
            "\t{",
            *binding_rows,
            "\t};",
            *case_assertions,
            f"\tconstexpr Projection::LayoutCase g_{module}LayoutCases[] =",
            "\t{",
            *case_rows,
            "\t};",
            f"\tconstexpr Projection::LayoutSpec g_{module}LayoutSpecs[] =",
            "\t{",
            *layout_rows,
            "\t};",
            f"\tLONG g_{module}SelectedOffsets[std::size(g_{module}LayoutSpecs)]{{}};",
            f"\tbool g_{module}LayoutSupported[std::size(g_{module}LayoutSpecs)]{{}};",
            "}",
            "",
            f"namespace {namespace}",
            "{",
            f"\tconstinit Projection::ModuleRegistry g_registry{{",
            f"\t\t\"{'uDWM.dll' if module == 'udwm' else 'dwmcore.dll'}\",",
            f"\t\tGenerated::g_{module}StringPool, std::span{{Generated::g_{module}SymbolNameOffsets}}, std::span{{Generated::g_{module}Versions}},",
            f"\t\tstd::span{{Generated::g_{module}SymbolSpecs}},",
            f"\t\tstd::span{{Generated::g_{module}Candidates}}, std::span{{Generated::g_{module}Resolved}},",
            f"\t\tstd::span{{Generated::g_{module}ResolutionStates}}, std::span{{Generated::g_{module}Bindings}},",
            f"\t\tstd::span{{Generated::g_{module}LayoutSpecs}}, std::span{{Generated::g_{module}LayoutCases}},",
            f"\t\tstd::span{{Generated::g_{module}SelectedOffsets}}, std::span{{Generated::g_{module}LayoutSupported}}}};",
            "}",
            "",
        ])
    return "\n".join(lines)


def generate_files(schemas: Sequence[ProjectionSchema]) -> dict[str, str]:
    """Generate the complete, fixed output set for one architecture."""
    by_module = {schema["module"]: schema for schema in schemas}
    if tuple(by_module) != MODULES or len(by_module) != len(MODULES):
        raise ValueError(f"expected schemas in module order {MODULES}, got {tuple(by_module)}")
    return {
        "udwm.Layouts.generated.hpp": generate_layout_header(by_module["udwm"]),
        "udwm.Symbols.generated.hpp": generate_symbol_header(by_module["udwm"]),
        "dwmcore.Layouts.generated.hpp": generate_layout_header(by_module["dwmcore"]),
        "dwmcore.Symbols.generated.hpp": generate_symbol_header(by_module["dwmcore"]),
        "ProjectionRegistry.generated.inc": generate_registry_inc(schemas),
    }
