"""Validate and emit exact PE/PDB symbol-resolution catalogs."""

from __future__ import annotations

import hashlib
import json
import re
import uuid
from pathlib import Path
from typing import Any, Sequence

import projection_schema
from projection_schema import ProjectionSchema, SchemaError, Symbol, SymbolBinding, Version


SCHEMA_VERSION = 1
UINT32_MAX = 0xFFFFFFFF
SHA256_RE = re.compile(r"[0-9a-fA-F]{64}\Z")
STATUSES = {"unique", "missing", "ambiguous"}
GENERATED_NOTICE = "// Generated by Scripts/projection_codegen.py. Do not edit."


def _keys(value: dict[str, Any], allowed: set[str], context: str) -> None:
    unknown = set(value) - allowed
    missing = allowed - set(value)
    if unknown:
        raise SchemaError(f"{context}: unknown properties: {', '.join(sorted(unknown))}")
    if missing:
        raise SchemaError(f"{context}: missing properties: {', '.join(sorted(missing))}")


def _uint(value: Any, maximum: int, context: str, *, nonzero: bool = False) -> int:
    if isinstance(value, bool) or not isinstance(value, int) or value < 0 or value > maximum or (nonzero and value == 0):
        qualifier = "nonzero " if nonzero else ""
        raise SchemaError(f"{context} must be a {qualifier}unsigned integer no greater than {maximum}")
    return value


def _string(value: Any, context: str) -> str:
    if not isinstance(value, str) or not value:
        raise SchemaError(f"{context} must be a non-empty string")
    return value


def _sha256(value: Any, context: str) -> str:
    result = _string(value, context).lower()
    if not SHA256_RE.fullmatch(result):
        raise SchemaError(f"{context} must contain 64 hexadecimal characters")
    return result




def _in_range(version: Version, item: dict[str, Any]) -> bool:
    minimum = projection_schema.parse_version(item.get("min_inclusive"), "min_inclusive")
    maximum = projection_schema.parse_version(item.get("max_exclusive"), "max_exclusive")
    return (not minimum.build or version >= minimum) and (not maximum.build or version < maximum)


def _selected_binding(symbol: Symbol, version: Version, configuration: str) -> tuple[int, SymbolBinding] | None:
    if symbol.get("condition") == "debug" and configuration != "debug":
        return None
    for index, binding in enumerate(symbol["bindings"]):
        if _in_range(version, binding):
            return index, binding
    return None


def _contract_rows(schema: ProjectionSchema, version: Version, configuration: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for symbol in schema["symbols"]:
        selected = _selected_binding(symbol, version, configuration)
        if selected is None:
            continue
        binding_index, binding = selected
        rows.append({
            "id": symbol["id"],
            "kind": symbol["kind"],
            "type": symbol.get("type"),
            "usage": symbol.get("usage"),
            "requirement": symbol["requirement"],
            "condition": symbol.get("condition"),
            "abi_compatibility": symbol.get("abi_compatibility"),
            "binding_index": binding_index,
            "min_inclusive": binding.get("min_inclusive"),
            "max_exclusive": binding.get("max_exclusive"),
            "symbol_names": binding["symbol_names"],
        })
    return rows


def resolution_contract(schema: ProjectionSchema, version: Version, configuration: str) -> str:
    encoded = json.dumps(
        _contract_rows(schema, version, configuration),
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=True,
    ).encode("utf-8")
    return hashlib.sha256(encoded).hexdigest()


def _read_object(path: Path, context: str) -> dict[str, Any]:
    value = projection_schema.read_json(path)
    return projection_schema.require_object(value, context)


def resolver_identity(value: Any, context: str) -> dict[str, str]:
    resolver = projection_schema.require_object(value, context)
    _keys(resolver, {"dbghelp"}, context)
    dbghelp = projection_schema.require_object(resolver["dbghelp"], f"{context}.dbghelp")
    _keys(dbghelp, {"version", "sha256"}, f"{context}.dbghelp")
    return {
        "version": _string(dbghelp["version"], f"{context}.dbghelp.version"),
        "sha256": _sha256(dbghelp["sha256"], f"{context}.dbghelp.sha256"),
    }


def _normalize_records(
    records: list[Any],
    schema: ProjectionSchema,
    source: Path,
    module: str,
    build: int,
) -> list[dict[str, Any]]:
    normalized: list[dict[str, Any]] = []
    identities: set[tuple[Any, ...]] = set()
    image_hashes: set[str] = set()
    for record_index, raw_record in enumerate(records):
        context = f"{source}.records[{record_index}]"
        record = projection_schema.require_object(raw_record, context)
        _keys(record, {"revision", "image", "pdb", "resolution_contract", "symbols"}, context)
        revision = _uint(record["revision"], UINT32_MAX, f"{context}.revision")
        version = Version(build, revision)
        if not _in_range(version, schema):
            raise SchemaError(f"{context}: version is outside the {module} schema range")

        image = projection_schema.require_object(record["image"], f"{context}.image")
        _keys(image, {"time_date_stamp", "size_of_image", "sha256"}, f"{context}.image")
        timestamp = _uint(image["time_date_stamp"], UINT32_MAX, f"{context}.image.time_date_stamp")
        image_size = _uint(image["size_of_image"], UINT32_MAX, f"{context}.image.size_of_image", nonzero=True)
        image_hash = _sha256(image["sha256"], f"{context}.image.sha256")
        if image_hash in image_hashes:
            raise SchemaError(f"{context}: duplicate PE SHA-256 in source")
        image_hashes.add(image_hash)

        pdb = projection_schema.require_object(record["pdb"], f"{context}.pdb")
        _keys(pdb, {"name", "guid", "age", "sha256"}, f"{context}.pdb")
        pdb_name = _string(pdb["name"], f"{context}.pdb.name")
        if Path(pdb_name).name != pdb_name or any(ord(character) < 0x20 or ord(character) > 0x7E for character in pdb_name):
            raise SchemaError(f"{context}.pdb.name must be a printable ASCII basename")
        try:
            pdb_guid = str(uuid.UUID(_string(pdb["guid"], f"{context}.pdb.guid")))
        except ValueError as error:
            raise SchemaError(f"{context}.pdb.guid must be a GUID") from error
        pdb_age = _uint(pdb["age"], UINT32_MAX, f"{context}.pdb.age", nonzero=True)
        pdb_hash = _sha256(pdb["sha256"], f"{context}.pdb.sha256")


        expected_contract = resolution_contract(schema, version, "release")
        if record["resolution_contract"] != expected_contract:
            raise SchemaError(f"{context}.resolution_contract is stale for the active projection bindings")
        active: dict[str, tuple[int, Symbol, SymbolBinding]] = {}
        for symbol_index, symbol in enumerate(schema["symbols"]):
            selected = _selected_binding(symbol, version, "release")
            if selected is not None:
                active[symbol["id"]] = (symbol_index, symbol, selected[1])

        raw_symbols = projection_schema.require_object(record["symbols"], f"{context}.symbols")
        entries: list[dict[str, Any]] = []
        for symbol_id, raw_symbol_record in raw_symbols.items():
            symbol_context = f"{context}.symbols.{symbol_id}"
            if symbol_id not in active:
                raise SchemaError(f"{symbol_context}: Symbol is not active for this version")
            symbol_index, symbol, binding = active[symbol_id]
            symbol_record = projection_schema.require_object(raw_symbol_record, symbol_context)
            _keys(symbol_record, {"name", "rva"}, symbol_context)
            matched_name = _string(symbol_record["name"], f"{symbol_context}.name")
            if matched_name not in binding["symbol_names"]:
                raise SchemaError(f"{symbol_context}.name is not in the selected binding")
            rva_text = _string(symbol_record["rva"], f"{symbol_context}.rva")
            try:
                rva = int(rva_text, 0)
            except ValueError as error:
                raise SchemaError(f"{symbol_context}.rva must be a C-style integer string") from error
            _uint(rva, UINT32_MAX, f"{symbol_context}.rva", nonzero=True)
            if rva >= image_size:
                raise SchemaError(f"{symbol_context}.rva is outside SizeOfImage")
            entries.append({"symbol_index": symbol_index, "rva": rva})
        entries.sort(key=lambda entry: entry["symbol_index"])

        missing_required = {
            symbol_id
            for symbol_id, (_, symbol, _) in active.items()
            if symbol["requirement"] == "required" and symbol_id not in raw_symbols
        }
        if missing_required:
            raise SchemaError(f"{context}.symbols omits Required IDs: {', '.join(sorted(missing_required))}")

        identity = (module, 0x8664, timestamp, image_size, pdb_guid, pdb_age, pdb_name.casefold())
        if identity in identities:
            raise SchemaError(f"{context}: duplicate exact module identity")
        identities.add(identity)
        normalized.append({
            "module": module,
            "version": version,
            "configuration": "release",
            "machine": 0x8664,
            "time_date_stamp": timestamp,
            "size_of_image": image_size,
            "image_sha256": image_hash,
            "pdb_name": pdb_name,
            "pdb_guid": pdb_guid,
            "pdb_age": pdb_age,
            "pdb_sha256": pdb_hash,
            "resolution_contract": expected_contract,
            "entries": entries,
        })
    return normalized


def load_catalog_sources(index: Path, architecture: str, schemas: Sequence[ProjectionSchema]) -> dict[str, Any]:
    raw_index = _read_object(index, str(index))
    _keys(raw_index, {"schema_version", "architecture", "resolver", "sources"}, str(index))
    if raw_index["schema_version"] != SCHEMA_VERSION:
        raise SchemaError(f"{index}: schema_version must be {SCHEMA_VERSION}")
    if raw_index["architecture"] != architecture:
        raise SchemaError(f"{index}: architecture must be {architecture}")
    resolver = resolver_identity(raw_index["resolver"], f"{index}.resolver")
    schemas_by_module = {schema["module"]: schema for schema in schemas}
    if set(schemas_by_module) != {"udwm", "dwmcore"}:
        raise SchemaError(f"{index}: schemas must contain udwm and dwmcore")

    required_sources = {
        (module, build)
        for module, schema in schemas_by_module.items()
        for build in schema["known_builds"]
    }
    source_values = projection_schema.require_list(raw_index["sources"], f"{index}.sources")
    seen_paths: set[Path] = set()
    seen_keys: set[tuple[str, int]] = set()
    evidence_hashes: set[str] = set()
    evidence_identities: set[tuple[Any, ...]] = set()
    normalized: list[dict[str, Any]] = []
    for source_index, value in enumerate(source_values):
        relative = _string(value, f"{index}.sources[{source_index}]")
        relative_path = Path(relative)
        if relative_path.is_absolute() or len(relative_path.parts) != 2 or relative_path.suffix.lower() != ".json":
            raise SchemaError(f"{index}.sources[{source_index}] must be module/BUILD.json")
        module = relative_path.parts[0]
        if module not in schemas_by_module or not relative_path.stem.isdigit():
            raise SchemaError(f"{index}.sources[{source_index}] must identify a known module and numeric build")
        build = int(relative_path.stem)
        key = (module, build)
        if key not in required_sources:
            raise SchemaError(f"{index}.sources[{source_index}]: module/build is not recognized by this architecture")
        path = (index.parent / relative_path).resolve()
        if path in seen_paths:
            raise SchemaError(f"{index}.sources[{source_index}]: duplicate source path")
        if key in seen_keys:
            raise SchemaError(f"{index}.sources[{source_index}]: duplicate source for {module} build {build}")
        seen_paths.add(path)
        seen_keys.add(key)

        source = _read_object(path, str(path))
        _keys(source, {"schema_version", "records"}, str(path))
        if source["schema_version"] != SCHEMA_VERSION:
            raise SchemaError(f"{path}: schema_version must be {SCHEMA_VERSION}")
        source_records = projection_schema.require_list(source["records"], f"{path}.records")
        source_normalized = _normalize_records(source_records, schemas_by_module[module], path, module, build)
        actual_hashes = {record["image_sha256"] for record in source_normalized}
        duplicate_evidence = evidence_hashes & actual_hashes
        if duplicate_evidence:
            raise SchemaError(f"{path}: PE hashes appear in multiple evidence sources: {sorted(duplicate_evidence)}")
        evidence_hashes.update(actual_hashes)
        for record in source_normalized:
            identity = (
                record["module"], record["machine"], record["time_date_stamp"], record["size_of_image"],
                record["pdb_guid"], record["pdb_age"], record["pdb_name"].casefold(),
            )
            if identity in evidence_identities:
                raise SchemaError(f"{path}: duplicate exact module identity across evidence sources")
            evidence_identities.add(identity)
        normalized.extend(source_normalized)
    if seen_keys != required_sources:
        missing = [f"{module}/{build}" for module, build in sorted(required_sources - seen_keys)]
        raise SchemaError(f"{index}: missing explicitly indexed sources: {', '.join(missing)}")

    normalized.sort(key=lambda item: (
        item["module"], item["version"].build, item["version"].revision,
        item["image_sha256"], item["pdb_guid"], item["pdb_age"],
    ))
    return {
        "architecture": architecture,
        "resolver": resolver,
        "symbol_counts": {module: len(schema["symbols"]) for module, schema in schemas_by_module.items()},
        "records": normalized,
    }

def _guid_initializer(value: str) -> str:
    guid = uuid.UUID(value)
    data = guid.bytes_le
    data1 = int.from_bytes(data[0:4], "little")
    data2 = int.from_bytes(data[4:6], "little")
    data3 = int.from_bytes(data[6:8], "little")
    data4 = ", ".join(f"0x{byte:02X}" for byte in data[8:16])
    return f"{{0x{data1:08X}, 0x{data2:04X}, 0x{data3:04X}, {{{data4}}}}}"


def generate_files(catalog: dict[str, Any]) -> dict[str, str]:
    strings = "\0"
    offsets: dict[str, int] = {}
    entries: list[int] = []
    record_rows: list[str] = []
    for record in catalog["records"]:
        name = record["pdb_name"]
        if name not in offsets:
            offsets[name] = len(strings)
            strings += name + "\0"
        dense_entries = [0] * catalog["symbol_counts"][record["module"]]
        for entry in record["entries"]:
            if entry["symbol_index"] >= len(dense_entries) or dense_entries[entry["symbol_index"]]:
                raise SchemaError("catalog record has an invalid or duplicate Symbol index")
            dense_entries[entry["symbol_index"]] = entry["rva"]
        first_entry = len(entries)
        entries.extend(dense_entries)
        if offsets[name] > UINT32_MAX or first_entry > UINT32_MAX or len(dense_entries) > UINT32_MAX:
            raise SchemaError("generated catalog exceeds 32-bit record limits")
        module = "uDWM" if record["module"] == "udwm" else "DwmCore"
        version = record["version"]
        record_rows.append(
            "\t\t{" +
            f"Projection::ModuleId::{module}, {record['machine']}u, {record['time_date_stamp']}u, {record['size_of_image']}u, " +
            f"{_guid_initializer(record['pdb_guid'])}, {record['pdb_age']}u, {offsets[name]}u, " +
            f"{{{version.build}u, {version.revision}u}}, {first_entry}u, {len(dense_entries)}u" +
            "},"
        )
    escaped = strings.replace("\\", "\\\\").replace('"', '\\"').replace("\0", "\\0")
    entry_rows = [
        f"\t\t0x{rva:X}u,"
        for rva in entries
    ]
    record_storage = record_rows or ["\t\t{},"]
    entry_storage = entry_rows or ["\t\t{},"]
    record_count = len(record_rows)
    entry_count = len(entry_rows)
    header = "\n".join([
        GENERATED_NOTICE, "#pragma once", "", "namespace OpenGlass::Projection", "{",
        "\textern const SymbolCatalog g_builtInSymbolCatalog;", "}", "",
    ])
    implementation = "\n".join([
        GENERATED_NOTICE, "", "namespace OpenGlass::Projection::Generated", "{",
        f"\tconstexpr WCHAR g_symbolCatalogStrings[] = L\"{escaped}\";",
        "\tconstexpr Projection::SymbolCatalogRecord g_symbolCatalogRecords[] =", "{",
        *record_storage, "\t};", "\tconstexpr UINT32 g_symbolCatalogEntries[] =", "\t{",
        *entry_storage, "\t};", "}", "", "namespace OpenGlass::Projection", "{",
        "\tconst SymbolCatalog g_builtInSymbolCatalog", "\t{",
        "\t\tGenerated::g_symbolCatalogStrings, std::size(Generated::g_symbolCatalogStrings),",
        f"\t\tstd::span{{Generated::g_symbolCatalogRecords}}.first({record_count}),",
        f"\t\tstd::span{{Generated::g_symbolCatalogEntries}}.first({entry_count})", "\t};", "}", "",
    ])
    return {"SymbolCatalog.generated.hpp": header, "SymbolCatalog.generated.inc": implementation}
